services:
  - type: web
    name: squidex-proxy
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SQUIDEX_DOMAIN
        value: squidex.onrender.com
      - key: SQUIDEX_ADMINEMAIL
        value: admin@squidex.io
      - key: SQUIDEX_ADMINPASSWORD
        value: admin